# Generated by Django 3.2.9 on 2022-04-17 06:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the base problem (e.g. Quadratic Equation)', max_length=50)),
                ('problem_module', models.CharField(max_length=100)),
                ('problem_function', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a tag name(s) (e.g. Maths, Year 7, Functions)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular generated problem across whole application', primary_key=True, serialize=False)),
                ('variables', models.CharField(help_text='Enter the variables separated by commas', max_length=100)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trainer.problem')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='tag',
            field=models.ManyToManyField(help_text='Select tags for this problem', to='trainer.Tag'),
        ),
    ]
