# Generated by Django 4.0.3 on 2022-05-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_function',
            field=models.CharField(help_text='gen_problem', max_length=100),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_module',
            field=models.CharField(help_text='eg: koios_webapp.problems.quadratic_trainer', max_length=100),
        ),
    ]
