# Generated by Django 3.2.9 on 2022-04-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_timetaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetaken',
            name='time',
            field=models.FloatField(),
        ),
    ]
